### ISSUE TITLE
File Upload fails with "Converting circular structure to JSON" error

### ISSUE THREAD

**Issue by ebbbang** [ndianabasi/adonis-responsive-attachment#9]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

- Lots of raised issues are directly not bugs but instead are design decisions taken by us.
- Make use of our [forum](https://forum.adonisjs.com/), or [discord server](https://discord.me/adonisjs), if you are not sure that you are reporting a bug.
- Ensure the issue isn't already reported.
- Ensure you are reporting the bug in the correct repo.

*Delete the above section and the instructions in the sections below before submitting*

## Package version
1.3.0

## Node.js and npm version
Node: v16.15.0 | NPM: 8.5.5

## Sample Code (to reproduce the issue)
Upload any file using .fromFile function and having @responsiveAttachment() decorator disk to 's3' and having DISK_DRIVE in .env to 's3'.
The issue is that the relativepath in ResponsiveAttachment constructor creates folder with double tmp folder prefix.
E.g. image_upload_tmp/image_upload_tmp/cl4y2sz090001s7xl0sfw6lsq.jpg
This only happens when the decorator and env has s3 as the disk type

**Comment by ebbbang** [comment]
Duplicate #6

**Comment by ndianabasi** [comment]
Fixed by https://github.com/ndianabasi/adonis-responsive-attachment/pull/10
